Updated Code to Collection Lambda Function Data for use in the Graviton Opportunities Dashboard
awslabs/cid-framework pull request #136
Opened 2024-06-04 18:29 UTC by erikpeteaws

*Issue #, if available:* none

*Description of changes:*
module-inventory.yaml
Line 57: Add lambda as an Object to list
Line 843: update code for lambda

deploy-in-linked-account.yaml
Line 176: add Lambda list-function call to IAM role

module-pricing.yaml
Line 38: add Lambda to list of services

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-06 19:21 UTC, esc1144 requested changes
You need to update the Mappings in the pricing module to include an entry for the AWSLambda construct. Although my deploy failed there before the inventory module, it looks like you need to create a Mappings entry for the Lambda table construct, as with the other services sub-modules

Here is the CloudFormation error in the pricing module:

> Transform AWS::LanguageExtensions failed with: Mappings not found in template for key /AWSLambda/path on resourceType Fn::ForEach::Service field forEach

2024-06-07 16:53 UTC, erikpeteaws commented
resolving mapping issue identified with initial pull request. Mapping updated in both inventory and pricing modules for AWSLambda

2024-06-21 07:42 UTC, iakov-aws commented on data-collection/deploy/module-inventory.yaml
> +  AWSLambda:
```suggestion
    AWSLambda:
```

2024-06-21 08:23 UTC, iakov-aws commented
fixed a few minor things and merged here -> https://github.com/awslabs/cid-framework/pull/142

2024-06-21 08:23 UTC, closed without merging